### ISSUE TITLE
Public Repository

### ISSUE THREAD

**Issue by jembie** [Trivo25/vue-snarkyjs-template#1]
Your repository is public, but it's supposed to be private, here's how you can change it:

1. On GitHub.com, navigate to the main page of the repository.

2. Under your repository name, click  Settings.

3. Under "Danger Zone", to the right of to "Change repository visibility", click Change visibility.

4. Select a visibility.

5. To verify that you're changing the correct repository's visibility, type the name of the repository you want to change the visibility of.

6. Click I understand, change repository visibility.

**Comment by Trivo25** [comment]
danke Ray
